# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dylan's Blog
email: dverrezen@gmail.com
description: >
        
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dylanv.github.io" # the base hostname & protocol for your site
paginate: 1 # The number of posts to show per page on your homepage

name: 'Dylan Verrezen'
bio: >
        Machine learning practitioner in Cape Town, South Africa.
        Currently working in healthcare.
author_image: "/assets/images/author.jpg"
twitter_username: 
github_username: dylanv

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  parse_block_html: true
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-paginate
